import Header from '@/components/Header'

import { Inter } from 'next/font/google'

import StyledComponentsRegistry from '@/lib/registry'

import Head from './head'

import ReduxProvider from '@/lib/redux'
import React from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Home - SpaceX",
  description: "Generated by Oman",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <Head />
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <ReduxProvider>
            <Header />
            <main>
              { children }
            </main>
          </ReduxProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
